/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=3f23113b&sid=33fe6aa3
 */
export interface ButtonProps {
  variant: "primary" | "secondary";
  children: React.ReactNode;
  onClick?: () => void;
  disabled?: boolean;
  ariaLabel?: string;
}

export interface AlertProps {
  icon: string;
  content: string;
  ariaLabel?: string;
}

export interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  children: React.ReactNode;
}
