/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface BetInputProps {
  name: string;
  value: string;
  onChange: (e: React.ChangeEvent<HTMLTextAreaElement>) => void;
}

const BetInput: React.FC<BetInputProps> = ({ name, value, onChange }) => {
  return (
    <div className="flex flex-col mt-2 w-full min-h-[93px]">
      <label
        htmlFor="bet"
        className="flex gap-1 items-center w-full text-base tracking-normal leading-none text-gray-400 whitespace-nowrap"
      >
        Bet*
      </label>
      <textarea
        required
        name={name}
        value={value}
        onChange={onChange}
        className="flex overflow-hidden mt-1 w-full text-xs tracking-normal leading-loose rounded-lg border border-solid shadow-sm  border-white border-opacity-10 bg-neutral-800 min-h-[69px] text-stone-500 p-4 pt-2"
        placeholder="Enter your Text Here"
      />
    </div>
  );
};

export default BetInput;
