/**
 * This code was generated by Builder.io.
 */
import React from "react";

const BetInput: React.FC = () => {
  return (
    <div className="flex flex-col mt-2 w-full min-h-[93px]">
      <label
        htmlFor="bet"
        className="flex gap-1 items-center w-full text-base tracking-normal leading-none text-gray-400 whitespace-nowrap"
      >
        Bet*
      </label>
      <textarea
        id="bet"
        className="flex overflow-hidden mt-1 w-full text-xs tracking-normal leading-loose rounded-lg border border-solid shadow-sm bg-white bg-opacity-0 border-white border-opacity-10 min-h-[69px] text-stone-500 p-4"
        placeholder="Enter your Text Here"
      />
    </div>
  );
};

export default BetInput;
