/**
 * This code was generated by Builder.io.
 */
import React from "react";

const InfoBox: React.FC = () => {
  return (
    <div className="flex gap-1 items-start px-2 py-3 mt-2 w-full text-xs tracking-normal leading-4 text-gray-500 rounded-xl border border-solid bg-neutral-800 border-zinc-800">
      <p className="flex flex-col flex-1 shrink w-full basis-0 min-w-[240px]">
        Duels Must go through a 3 Hour Bootstrapping Phase, if volume does not
        exceed $10,000 the collateral is returned The Duel May be closed by team
        if it is against our{" "}
        <a href="#" className="underline">
          guidelines
        </a>
      </p>
    </div>
  );
};

export default InfoBox;
