/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface MarketOptionProps {
  title: string;
  description: string;
  imageSrc: string;
  isSelected: boolean;
  onSelect: () => void;
}

const MarketOption: React.FC<MarketOptionProps> = ({
  title,
  description,
  imageSrc,
  isSelected,
  onSelect,
}) => {
  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <button
        onClick={onSelect}
        className={`flex grow gap-2 items-start text-center text-gray-500 min-h-[142px] w-full ${
          isSelected ? " bg-[#F19ED233] text-white rounded-xl" : ""
        }`}
      >
        <div className="flex flex-col flex-1 shrink w-full basis-0">
          <div className="flex overflow-hidden flex-col justify-center items-center py-4 w-full rounded-lg border border-solid shadow-sm bg-white bg-opacity-0 border-zinc-700 border-opacity-20">
            <img
              loading="lazy"
              src={imageSrc}
              alt=""
              className="object-contain aspect-square w-[42px]"
            />
            <h2 className="flex items-center mt-1 max-w-full text-lg font-medium tracking-normal leading-none w-[124px]">
              <span className="flex flex-1 shrink gap-2.5 justify-center items-center self-stretch my-auto w-full basis-0">
                <span className="self-stretch my-auto w-[110px]">{title}</span>
              </span>
            </h2>
            <p className="flex gap-2.5 items-start self-stretch px-2 mt-1 w-full text-xs tracking-normal leading-4">
              <span className="flex-1 shrink w-full">{description}</span>
            </p>
          </div>
        </div>
      </button>
    </div>
  );
};

export default MarketOption;
