/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ProgressBar: React.FC = () => {
  return (
    <div
      className="flex gap-2 items-start px-28 py-3 w-full"
      role="progressbar"
      aria-valuenow={33}
      aria-valuemin={0}
      aria-valuemax={100}
    >
      <div className="flex flex-1 shrink bg-pink-300 rounded-md basis-0 h-[5px] w-[63px]" />
      <div className="flex flex-1 shrink w-16 rounded-md basis-0 bg-zinc-700 h-[5px]" />
      {/* <div className="flex flex-1 shrink rounded-md basis-0 bg-zinc-700 h-[5px] w-[63px]" /> */}
    </div>
  );
};

export default ProgressBar;
