/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface HeaderProps {
  onClose: () => void;
}

const Header: React.FC<HeaderProps> = ({ onClose }) => {
  return (
    <header className="flex justify-end mt-[3px] mr-[12px] w-full ">
      <img
      onClick={onClose}
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c8454ace92408c5f78a561826e30af0ccb24a17e06e7bdcde242966a7eca23a8?placeholderIfAbsent=true&apiKey=9a4d3cdfd283475dbc30e1b60dc2077d"
        alt=""
        className="object-contain w-7 aspect-square fill-white fill-opacity-10 stroke-[1px] stroke-white stroke-opacity-0"
      />
      {/* <button
        onClick={onClose}
        className="text-white hover:text-gray-300 focus:outline-none"
        aria-label="Close modal"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className="h-6 w-6"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M6 18L18 6M6 6l12 12"
          />
        </svg>
      </button> */}
    </header>
  );
};

export default Header;
