/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface DuelCategoryCardProps {
  title: string;
  imageSrc?: string;
  isSpecial?: boolean;
}

const DuelCategoryCard: React.FC<DuelCategoryCardProps> = ({
  title,
  imageSrc,
  isSpecial,
}) => {
  const baseClasses =
    "flex overflow-hidden grow shrink self-stretch pl-4 my-auto rounded-xl border-2 border-solid min-w-[240px] w-[226px]";
  const specialClasses =
    "px-4 pt-28 pb-2 text-pink-300 border-pink-300 shadow-sm bg-[linear-gradient(180deg,#101010_0%,#000_100%)] max-md:pt-24 max-md:pr-5";
  const regularClasses = "border-zinc-700";

  return (
    <section
      className={`${baseClasses} ${
        isSpecial ? specialClasses : regularClasses
      }`}
    >
      {!isSpecial && (
        <>
          <h2 className="z-10 grow self-end mt-28 max-md:mt-10 max-md:mr-0">
            {title}
          </h2>
          {imageSrc && (
            <img
              loading="lazy"
              src={imageSrc}
              alt=""
              className="object-contain shrink-0 max-w-full aspect-[1.05] w-[188px]"
            />
          )}
        </>
      )}
      {isSpecial && <h2>{title}</h2>}
    </section>
  );
};

export default DuelCategoryCard;
