/**
 * This code was generated by Builder.io.
 */
"use client"
import React from "react";
import { useRouter } from "next/navigation";


const Logo: React.FC = () => {
  const router = useRouter();
  return (
    <img
      onClick={() => router.push("/")}
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/89a3435e93a53e2498fb83b43a64f7e7c9e9a70a892c901dd112ca1273e5638c?placeholderIfAbsent=true&apiKey=5395477fd4e141368e15c98db5e38353"
      alt="Company Logo"
      className="object-contain shrink-0 self-stretch my-auto rounded-none aspect-[2.86] w-[117px]"
    />
  );
};

export default Logo;
