/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SettingsIcon: React.FC = () => {
  return (
    <svg className="w-[32px] h-[32px]" xmlns="http://www.w3.org/2000/svg" width="32" height="33" viewBox="0 0 32 33" fill="none">
<path d="M5 8.5H27M5 16.5H27M5 24.5H27" stroke="#F3EFE0" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
    // <img
    //   loading="lazy"
    //   src="https://cdn.builder.io/api/v1/image/assets/TEMP/4460f5645f4eb845039ee01d8484164c5d429cb2e1d9ce389048d8ffec478c30?placeholderIfAbsent=true&apiKey=5395477fd4e141368e15c98db5e38353"
    //   alt="Settings"
    //   className="object-contain shrink-0 self-stretch my-auto w-8 aspect-square"
    // />
  );
};

export default SettingsIcon;
