/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ToggleButtonProps {
  isActive: boolean;
  onClick: () => void;
  children: React.ReactNode;
}

const ToggleButton: React.FC<ToggleButtonProps> = ({
  isActive,
  onClick,
  children,
}) => (
  <button
    className={`flex relative gap-4 items-start px-4 py-1 h-full leading-none rounded-lg w-[195px] ${
      isActive ? "text-gray-900" : "font-semibold text-stone-200"
    }`}
    onClick={onClick}
  >
    {isActive && (
      <div className="flex absolute inset-0 z-0 shrink-0 items-center self-start rounded-lg border-solid shadow-sm bg-[linear-gradient(180deg,#F19ED2_0%,#C87ECA_100%)] border-[0.5px] border-white border-opacity-10 h-[52px] w-[195px]" />
    )}
    <span className="z-0 my-auto text-ellipsis w-[163px]">{children}</span>
  </button>
);

interface DepositWithdrawToggleProps {
  activeTab: "deposit" | "withdraw";
  onTabChange: (tab: "deposit" | "withdraw") => void;
}

const DepositWithdrawToggle: React.FC<DepositWithdrawToggleProps> = ({
  activeTab,
  onTabChange,
}) => {
  return (
    <nav className="flex overflow-hidden justify-center text-base text-center whitespace-nowrap rounded-lg border border-solid bg-white bg-opacity-0 border-white border-opacity-10">
      <ToggleButton
        isActive={activeTab === "deposit"}
        onClick={() => onTabChange("deposit")}
      >
        Deposit
      </ToggleButton>
      <ToggleButton
        isActive={activeTab === "withdraw"}
        onClick={() => onTabChange("withdraw")}
      >
        Withdraw
      </ToggleButton>
    </nav>
  );
};

export default DepositWithdrawToggle;
