/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface DuelCardProps {
  title: string;
  imageSrc: string;
  volume: string;
  timeLeft: string;
  percentage: number;
  createdBy: string;
  creatorImageSrc?: string;
}

const DuelCard: React.FC<DuelCardProps> = ({
  title,
  imageSrc,
  volume,
  timeLeft,
  percentage,
  createdBy,
  creatorImageSrc,
}) => {
  const isPositive = percentage >= 50;
  const colorClass = isPositive ? "text-lime-300" : "text-red-500";
  const bgColorClass = isPositive ? "bg-lime-300" : "bg-red-500";

  return (
    <article className="flex flex-col flex-1 shrink self-stretch p-3 my-auto rounded-xl shadow basis-0 bg-zinc-900 min-w-[240px]">
      <div className="flex flex-col self-center max-w-full min-h-[114px] w-[227px]">
        <div className="flex gap-2 items-start w-full max-w-[227px]">
          <div className="flex gap-2 w-16 min-h-[64px]">
            <div className="flex flex-1 shrink basis-0 size-full">
              <div className="flex flex-1 shrink justify-center items-center w-16 h-16 bg-gray-500 rounded-lg border border-solid basis-0 border-white border-opacity-10">
                <img
                  loading="lazy"
                  src={imageSrc}
                  alt={title}
                  className="object-contain flex-1 shrink w-16 rounded-lg aspect-square basis-0"
                />
              </div>
            </div>
          </div>
          <h3 className="flex-1 shrink gap-2.5 self-stretch text-base font-semibold leading-none text-stone-200 w-[150px]">
            {title}
          </h3>
        </div>
        <div className="flex gap-3 mt-3 w-full">
          <div className="flex flex-col flex-1 shrink items-start self-start basis-0">
            <div className="flex gap-1 justify-center items-start text-xs tracking-normal leading-relaxed text-stone-200">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/6c6ce0714e0c999e8165254577c818af834576f42aac0d4273ddb19b1fc91a45?placeholderIfAbsent=true&apiKey=4bd09ea4570a4d12834637c604f75b6a"
                alt=""
                className="object-contain shrink-0 w-4 aspect-square"
              />
              <div>Volume: {volume}</div>
            </div>
            <div className="flex gap-1 mt-1 w-[87px]">
              <div className="flex gap-2.5 justify-center items-center py-0.5 w-4 h-full">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/20361b316e74c0a39ae0d9cfa0e04464d0ba3456555360296ff22210ea9118ca?placeholderIfAbsent=true&apiKey=4bd09ea4570a4d12834637c604f75b6a"
                  alt=""
                  className="object-contain self-stretch my-auto aspect-[0.92] w-[11px]"
                />
              </div>
              <div className="my-auto text-xs tracking-normal leading-relaxed text-stone-200">
                {timeLeft}
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center items-center w-[87px]">
            <div
              className={`text-base font-semibold leading-none ${colorClass}`}
            >
              {percentage} %
            </div>
            <div className="flex gap-0.5 mt-1 min-h-[13px] w-[62px]">
              {[...Array(10)].map((_, index) => (
                <div
                  key={index}
                  className={`flex flex-1 shrink ${
                    index < percentage / 10
                      ? bgColorClass
                      : "bg-gray-500 bg-opacity-30"
                  } rounded-xl basis-0 h-[13px] ${
                    index % 3 === 0 ? "w-[5px]" : "w-1"
                  }`}
                />
              ))}
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col mt-3 w-full text-base font-semibold leading-none whitespace-nowrap">
        <div className="flex gap-2 items-start w-full">
          <button className="flex-1 shrink gap-2.5 self-stretch p-2.5 text-lime-300 rounded-lg shadow-sm bg-lime-500 bg-opacity-30">
            YES
          </button>
          <button className="flex-1 shrink gap-2.5 self-stretch p-2.5 text-center text-red-500 rounded-lg shadow-sm bg-red-600 bg-opacity-20 w-[29px]">
            NO
          </button>
        </div>
      </div>
      <div className="flex gap-10 justify-between items-center mt-3 w-full">
        <div className="gap-2.5 self-stretch my-auto text-xs tracking-normal leading-relaxed text-gray-400">
          Created By:{" "}
        </div>
        <div className="flex gap-1 items-center self-stretch my-auto">
          {creatorImageSrc && (
            <img
              loading="lazy"
              src={creatorImageSrc}
              alt={`${createdBy}'s profile`}
              className="object-contain shrink-0 self-stretch my-auto rounded-xl aspect-square w-[18px]"
            />
          )}
          <div className="gap-2.5 self-stretch my-auto text-xs tracking-normal leading-relaxed whitespace-nowrap text-stone-200">
            {createdBy}
          </div>
        </div>
      </div>
    </article>
  );
};

export default DuelCard;
