/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header/Header";
// import DuelGrid from "./DuelGrid";
import SearchBar from "./SearchBar";
import DuelGrid from "./DuelGrid";
// import DuelCategoryCard from "./DuelCategories/DuelCategoryCard";
import DuelCategories from "./DuelCategories/DuelCategories";

const MainContent: React.FC = () => {
  return (
    <main className="flex overflow-hidden flex-col pb-56 bg-neutral-900 max-md:pb-24">
      <Header />
      <DuelCategories />
      <div className="flex flex-wrap gap-10 justify-between self-center mt-4 w-full max-w-[1180px] max-md:max-w-full">
        <div className="flex overflow-hidden justify-center p-1 h-full text-base text-center rounded-lg border border-solid bg-white bg-opacity-0 border-white border-opacity-10 min-w-[240px] text-stone-200">
          <div className="flex relative gap-4 items-start px-4 py-1 h-full leading-none text-white rounded-lg">
            <div className="flex absolute inset-y-0 left-0 right-px z-0 shrink-0 items-center self-start rounded-lg border-solid shadow-sm bg-[linear-gradient(180deg,#F19ED2_0%,#C87ECA_100%)] border-[0.5px] border-black border-opacity-0 h-[42px] w-[100px]" />
            <div className="z-0 my-auto text-ellipsis">Live Duels</div>
          </div>
          <div className="flex shrink-0 my-auto w-px h-3 rounded-sm bg-blend-normal" />
          <div className="self-stretch px-4 py-1 h-full font-semibold leading-none whitespace-nowrap text-ellipsis">
            Bootstrapping
          </div>
          <div className="self-stretch px-2.5 py-1 h-full tracking-normal whitespace-nowrap text-ellipsis w-[121px]">
            Completed
          </div>
        </div>
        <SearchBar />
      </div>
      <DuelGrid />
    </main>
  );
};

export default MainContent;
