/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ExportWalletButton from "./ExportWalletButton";

const MyComponent: React.FC = () => {
  return (
    <main>
      <ExportWalletButton
        text="Export Wallet"
        iconSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/a630edbe4c1b6250a9ffa2c38ddeef82640ee8cd5523bd8dbc4f255c74bb03b3?placeholderIfAbsent=true&apiKey=9a4d3cdfd283475dbc30e1b60dc2077d"
      />
    </main>
  );
};

export default MyComponent;
