/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchBar: React.FC = () => {
  return (
    <form className="flex gap-10 items-center px-5 py-2 my-auto rounded-xl border border-solid bg-white bg-opacity-0 border-white border-opacity-10 min-h-[50px] min-w-[240px] shadow-[0px_2px_10px_rgba(0,0,0,0.25)]">
      <label htmlFor="searchInput" className="sr-only">
        Search Duels
      </label>
      <input
        id="searchInput"
        type="text"
        placeholder="Search Duels"
        className="self-stretch my-auto text-xl text-stone-500 bg-transparent border-none outline-none"
      />
      <button type="submit" aria-label="Search">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/6791814555ad5f3f24d89ed7e8de36e8a73aa22d4e905aaaa793a3ff9a11f36a?placeholderIfAbsent=true&apiKey=4bd09ea4570a4d12834637c604f75b6a"
          alt=""
          className="object-contain self-stretch my-auto aspect-square w-[17px]"
        />
      </button>
    </form>
  );
};

export default SearchBar;
