/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TokenInput from "./TokenInput";
import PriceInput from "./PriceInput";
import WinConditionSelect from "./WinConditionSelect";
import DurationSelect from "./DurationSelect";
import InfoBox from "./InfoBox";
import CreateDuelButton from "./CreateDuelButton";

const CreateDuel: React.FC = () => {
  return (
    <section className="flex flex-col justify-center py-2.5 rounded-lg bg-zinc-900 max-w-[432px]">
      {/* <header className="flex relative gap-2.5 justify-center items-start py-2 w-full text-xl font-semibold text-center text-white border-b border-white border-opacity-10">
        <h1 className="z-0 flex-1 shrink my-auto w-full basis-0">
          Create a Duel
        </h1>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/4764d788ee8d6f9c7adf91bacacaecd1bf389d963670e3be0a15ddea081493ab?placeholderIfAbsent=true&apiKey=9a4d3cdfd283475dbc30e1b60dc2077d"
          alt=""
          className="object-contain absolute top-0.5 right-3 z-0 shrink-0 self-start w-7 h-7 aspect-square fill-white fill-opacity-10 stroke-[1px] stroke-white stroke-opacity-0"
        />
      </header> */}
      <main className="flex flex-col items-center self-center px-4 mt-4 w-full">
        <div className="flex gap-2 items-start px-28 py-3 max-w-full w-[400px]">
          <div className="flex flex-1 shrink bg-pink-300 rounded-md basis-0 h-[5px] w-[83px]" />
          <div className="flex flex-1 shrink bg-pink-300 rounded-md basis-0 h-[5px] w-[83px]" />
        </div>
        <form className="flex flex-col mt-2 w-full max-w-[400px]">
          <TokenInput />
          <div className="flex flex-col mt-4 w-full text-base tracking-normal leading-none">
            <div className="flex gap-1 items-center w-full">
              <div className="flex-1 shrink gap-1 self-stretch my-auto text-gray-400">
                Mark Price
              </div>
              <div className="flex-1 shrink gap-1 self-stretch my-auto text-white whitespace-nowrap">
                --
              </div>
            </div>
          </div>
          <PriceInput
            label="Trigger Price*"
            placeholder="Enter Trigger Price"
          />
          <PriceInput
            label="Minimum Wager Amount*"
            placeholder="Enter Minimum Bet Price"
          />
          <WinConditionSelect />
          <DurationSelect />
          <p className="self-start mt-4 text-xs font-medium tracking-normal leading-none text-center text-white">
            YES wins if mark price is <span className="underline">above</span>{" "}
            <span className="underline">[trigger price]</span> after{" "}
            <span className="underline">3 Hours</span>
          </p>
        </form>
        <InfoBox />
        <CreateDuelButton />
      </main>
    </section>
  );
};

export default CreateDuel;
