/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CreateDuelButton: React.FC = () => {
  return (
    <button
      type="submit"
      className="gap-2.5 self-stretch px-3 py-2.5 mt-4 w-full text-base font-semibold leading-none text-gray-900 rounded shadow-sm bg-[linear-gradient(180deg,#F19ED2_0%,#C87ECA_100%)] border-white border-opacity-70"
    >
      Create Duel
    </button>
  );
};

export default CreateDuelButton;
