/**
 * This code was generated by Builder.io.
 */
import React from "react";

const DurationSelect: React.FC = () => {
  const durations = ["3H", "6H", "12H", "24H", "48H"];

  return (
    <div className="flex flex-col mt-4 w-full">
      <div className="flex gap-1 items-center w-full">
        <label
          htmlFor="duration-select"
          className="flex flex-1 shrink gap-1 items-center self-stretch my-auto w-full basis-0 min-w-[240px]"
        >
          <span className="flex-1 shrink gap-1 self-stretch my-auto text-base tracking-normal leading-none text-gray-400">
            Ends in
          </span>
        </label>
        <div className="flex overflow-hidden justify-center self-stretch p-0.5 my-auto text-sm tracking-normal leading-none text-center whitespace-nowrap rounded-lg border border-solid bg-zinc-500 bg-opacity-10 border-gray-500 border-opacity-50 text-stone-200">
          {durations.map((duration, index) => (
            <button
              key={duration}
              type="button"
              className={`self-stretch px-2.5 py-1 h-full ${
                index === 0
                  ? "font-semibold bg-[linear-gradient(180deg,#F19ED2_0%,#C87ECA_100%)] rounded-lg"
                  : ""
              }`}
            >
              {duration}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
};

export default DurationSelect;
