/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=3f23113b&sid=33fe6aa3
 */
import * as React from "react";
import { ButtonProps } from "./types";

export const Button: React.FC<ButtonProps> = ({
  variant,
  children,
  onClick,
  disabled = false,
  ariaLabel,
}) => {
  const baseClasses =
    "flex flex-row justify-center items-center shrink px-3 py-5 h-full text-base font-semibold leading-none rounded-lg border-2 border-solid border-pink-300 min-w-[240px] transition-all duration-200";
  const variantClasses =
    variant === "primary"
      ? "text-gray-900 shadow-sm bg-[linear-gradient(180deg,#F19ED2_0%,#C87ECA_100%)]"
      : "text-pink-300 border-pink-300 bg-white bg-opacity-0 hover:bg-pink-300 hover:bg-opacity-10";

  return (
    <button
      onClick={onClick}
      disabled={disabled}
      aria-label={ariaLabel}
      className={`${baseClasses} ${variantClasses} ${
        disabled ? "opacity-50 cursor-not-allowed" : ""
      }`}
    >
      {children}
    </button>
  );
};
