/**
 * This code was generated by Builder.io.
 * https://builder.io/content/undefined?codeSession=3f23113b&sid=33fe6aa3
 */
import * as React from "react";
import { ModalProps } from "./types";

export const Modal: React.FC<ModalProps> = ({ isOpen, onClose, children }) => {
  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
    >
      <div className="relative" onClick={(e) => e.stopPropagation()}>
        {children}
      </div>
    </div>
  );
};
